#!/bin/bash

set -e

INFLUXDB_HOST=${INFLUXDB_PORT_8086_TCP_ADDR:-${INFLUXDB_HOST}}
INFLUXDB_HOST=${INFLUXDB_1_PORT_8086_TCP_ADDR:-${INFLUXDB_HOST}}
INFLUXDB_PORT=${INFLUXDB_PORT_8086_TCP_PORT:-${INFLUXDB_PORT}}
INFLUXDB_PORT=${INFLUXDB_1_PORT_8086_TCP_PORT:-${INFLUXDB_PORT}}
INFLUXDB_PASS=${INFLUXDB_ENV_INFLUXDB_INIT_PWD:-${INFLUXDB_PASS}}
INFLUXDB_PASS=${INFLUXDB_1_ENV_INFLUXDB_INIT_PWD:-${INFLUXDB_PASS}}

ELASTICSEARCH_USER=${ELASTICSEARCH_ENV_ELASTICSEARCH_USER:-${ELASTICSEARCH_USER}}
ELASTICSEARCH_USER=${ELASTICSEARCH_1_ENV_ELASTICSEARCH_USER:-${ELASTICSEARCH_USER}}
ELASTICSEARCH_PASS=${ELASTICSEARCH_ENV_ELASTICSEARCH_PASS:-${ELASTICSEARCH_PASS}}
ELASTICSEARCH_PASS=${ELASTICSEARCH_1_ENV_ELASTICSEARCH_PASS:-${ELASTICSEARCH_PASS}}

if [ "${ELASTICSEARCH_HOST}" == "**None**" ]; then
    unset ELASTICSEARCH_HOST
fi

if [ "${ELASTICSEARCH_PORT}" == "**None**" ]; then
    unset ELASTICSEARCH_PORT
fi

echo "${ELASTICSEARCH_USER}"
if [ "${ELASTICSEARCH_USER}" == "**None**" ]; then
    unset ELASTICSEARCH_USER
fi
echo "${ELASTICSEARCH_USER}"

echo "${ELASTICSEARCH_PASS}"
if [ "${ELASTICSEARCH_PASS}" == "**None**" ]; then
    unset ELASTICSEARCH_PASS
fi
echo "${ELASTICSEARCH_PASS}"

if [ "${HTTP_PASS}" == "**Random**" ]; then
    unset HTTP_PASS
fi

if [ ! -f /.basic_auth_configured ]; then
    /set_basic_auth.sh
fi

if [ ! -f /.influx_db_configured ]; then
    /set_influx_db.sh
fi

if [ ! -f /.elasticsearch_configured ]; then
    /set_elasticsearch.sh
fi

echo "=> Starting and running Nginx..."
/usr/sbin/nginx
